### ISSUE TITLE
Testing and CI

### ISSUE THREAD

**Issue by joaomcteixeira** [MDAnalysis/mdacli#10]
On top of #8 and #9 discussions, we need to agree on a strategy for testing and CI. Despite MDA_CLI being part of MDA and uses MDA it is independent of the main project, so I believe it should have its own testing and CI infrastructure. What do you think @orbeckst @PicoCentauri ?

On Travis-CI for `taurenmd` I use `tox-conda` to install MDAnalysis and perform `taurenmd` tests. It can be an option to reproduce that strategy here. We can also try Github Actions.

**Comment by orbeckst** [comment]
It should definitely have its own testing. If you already have a working strategy, then I would use it.

The parts in MDAnalysis.analysis that are required for mda_cli need to be tested in the MDA testsuite.

**Comment by joaomcteixeira** [comment]
Perfect, we will do as such,
I agree parts on MDAnalysis.analysis should be tested on the MDA testsuite. :+1:

**Comment by PicoCentauri** [comment]
What about using CI with the new GitHub actions. I am also happy if we use Travis for testing.

**Comment by joaomcteixeira** [comment]
I agree. We need to keep in mind to install MDAnalysis via Conda so it installs much faster.

@PicoCentauri what do you think on using `tox`? Have you use it before? If so, tox handles all this for us. Simply instead of running it on Travis we run it on GitHub Actions. Otherwise we can configure all steps manually directly on Actions.

**Comment by PicoCentauri** [comment]
No I never used `tox` if you have experience with that I trust you and we can use it. 🙃

**Comment by joaomcteixeira** [comment]
Heheh, perfect. So is on me to setup the github actions with all that :wink: I will try to PR this week

**Comment by joaomcteixeira** [comment]
Another question on this regard,
Should we keep the repository as simple as it is or should we create a complete module/package infrastructure?

Having the script around like `python cli_main.py` is awkward.

Also to integrate docs, tests, and future developments it is best to have the repository organized like a package so that people can even `pip install mda_cli` in the near future.

What do you think? If you agree with this setup I will arrange it.

Cheers,

**Comment by orbeckst** [comment]
It should definitely be `pip` and `conda` installable.

**Comment by PicoCentauri** [comment]
@orbeckst was a bit faster. 😂

I agree that we should build a whole module with a setup file.

**Comment by orbeckst** [comment]
I'd also use versioneer for versioning.

**Comment by orbeckst** [comment]
Setuptools has "entry points" that generate scripts, see e.g. https://github.com/jensengroup/propka/blob/810750cdd75845a60943d2fd5ed5b9c3e28802dd/setup.py#L57 . In this case your package contains a module with a `run()` or `main()` function that is called by the entry point.

**Comment by joaomcteixeira** [comment]
Jejej, I believe for @orbeckst is still September 8th :stuck_out_tongue: 

Perfect, so I will arrange that. I am used already to the entry points and the `pip`, I do it for my other projects.

For versioning I always use `bumpversion` but if you prefer versioneer, lets go for it. I am assuming we are with Semantic Version 2.0, right?

I never packaged for conda, I may need a little help on that, I will let you know. But that is good because I wanted to learn it :stuck_out_tongue_closed_eyes: 

I will PR asap in the next days,
cheers

**Comment by orbeckst** [comment]
SemVer all the way ;-)

I don't know bumpversion. We have just been using versioneer everywhere (except in MDAnalysis itself... the PR https://github.com/MDAnalysis/mdanalysis/pull/2121 is stalled because there were issues that I couldn't figure out with our complicated repo structure). And generally I've been very happy with versioneer.

We'll be happy to help with conda packaging — just another conda-forge project. We'll worry about it when it works from PyPi because conda-forge will simply pull from PyPi.

I'll be curious to see how GitHub actions works, I've seen it for some other repos but not really had time to figure it out myself.

**Comment by joaomcteixeira** [comment]
`bumpversion` is actually simple. It keeps a register where are all the strings in the repository containing version numbers and updates them on demand through CLI. Is control it manually for [taurenmd](https://github.com/joaomcteixeira/taurenmd/blob/master/.bumpversion.cfg), but we also have set up an automatic trigger with GitHub Actions, also with auto PyPi upload, in [pdb-tools](https://github.com/haddocking/pdb-tools/blob/master/.github/workflows/bump-version-on-push.yml). :wink:

I will have a look to see for `versioneer`.

When setting up the PyPi, which account are we going to register the software? Do you have a MDAnalysis main account for that?

Thanks for the help later on `conda`.

**Comment by orbeckst** [comment]
We don't have a special PyPi account. Set it up as owner and then add other people.

**Comment by orbeckst** [comment]
versioneer uses git tags as the sole authority for versions, works well because there's exactly one place where the version is set

**Comment by joaomcteixeira** [comment]
Hi All,

Sorry for having left this issue abandoned. The beginning of the semester has been a bit crazy. My entire fault. I have been looking today to the `tox` in git actions, and it looks quite straight forward. So I will just apply that strategy. :crossed_fingers: I can send it over the next days.

https://github.com/ymyzk/tox-gh-actions

https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python

Cheers :beers:

**Comment by joaomcteixeira** [comment]
I am preparing the CI services for this repository in a branch in my fork:

https://github.com/joaomcteixeira/mda_cli/tree/ci_services

Feel welcomed to comment and commit there.

By now I am configuring the repo for `bump2version`. We can later change to versioneer. Yet, the versioning in `mdacli` is independent of `MDAnalysis`. I am setting up the CI infrastructure according to [my preferred configurations](https://github.com/joaomcteixeira/python-project-skeleton).

Cheers, and we are back to the road :car: :smiley:

**Comment by PicoCentauri** [comment]
Hey @joaomcteixeira, 

the fork looks good! I have a few minor comments. Why don't you create a PR an we can quickly merge this important step forward.

**Comment by joaomcteixeira** [comment]
Thx @PicoCentauri 
Sorry I have been hit by another :ocean: :ocean: :books:
will finish and PR asap.
Cheers!!

**Comment by joaomcteixeira** [comment]
Implementations on #19 have been working great ever since. I consider this issue closed. If any modifications are needed in the future we can reopen it.
