### ISSUE TITLE
mdacli.mdanalysis.org no longer works for docs

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdacli#103]
I think #101 and deletion of the `gh-pages` branch means that `mdacli.mdanalysis.org` is now showing some random not-MDA website. The solution here is probably to point `mdacli.mdanalysis.org` to https://mdacli.readthedocs.io/ using the [ReadTheDocs subdomain](https://docs.readthedocs.io/en/stable/custom-domains.html). @PicoCentauri @joaomcteixeira I think only you two have maintainer access to RTD, so you might have to add someone or do it yourselves :)

**Comment by lilyminium** [comment]
In the meantime I took the liberty of changing the repo URL to https://mdacli.readthedocs.io/en/latest/ just to avoid serving spam.

**Comment by orbeckst** [comment]
@PicoCentauri @joaomcteixeira can I ask why you moved the docs to RTD? Was GH pages not working anymore?

Also, if the docs are really served from RTD, you need to **consider the privacy implications**. We as the MDAnalysis org as a NF-sponsored project **must** have a privacy policy and we must abide by it (and by NF's privacy policy). See the footer:

> Please see our [Privacy Policy](https://www.mdanalysis.org/pages/privacy/) to learn how [MDAnalysis](https://www.mdanalysis.org/) collects data.

Given that mdacli is hosted under the MDAnalysis org, I consider that we as MDAnalysis are still responsible for the docs. Thus, you — @joaomcteixeira and @PicoCentauri — need to do a privacy analysis of what data is collected and make a PR against our Privacy Policy https://www.mdanalysis.org/pages/privacy/ to update it.

(Opinions @lilyminium @IAlibay ?)

**Comment by PicoCentauri** [comment]
> @PicoCentauri @joaomcteixeira can I ask why you moved the docs to RTD? Was GH pages not working anymore?
> 

Yes, the GH pages action was not working anymore and I had no time so far to fix it. 

> Also, if the docs are really served from RTD, you need to **consider the privacy implications**. We as the MDAnalysis org as a NF-sponsored project **must** have a privacy policy and we must abide by it (and by NF's privacy policy). See the footer:
> 
> > Please see our [Privacy Policy](https://www.mdanalysis.org/pages/privacy/) to learn how [MDAnalysis](https://www.mdanalysis.org/) collects data.
> 
> Given that mdacli is hosted under the MDAnalysis org, I consider that we as MDAnalysis are still responsible for the docs. Thus, you — @joaomcteixeira and @PicoCentauri — need to do a privacy analysis of what data is collected and make a PR against our Privacy Policy https://www.mdanalysis.org/pages/privacy/ to update it.
> 
> (Opinions @lilyminium @IAlibay ?)

No, that is not the plan to ship it totally with RTD.

**Comment by joaomcteixeira** [comment]
Hi everyone,

was this fixed already? I see RTD pages work well. I can add you as admins to the RTD mdacli project.

**Comment by orbeckst** [comment]
The point was that we'd rather _not_ have RTD pages for MDAnalysis-branded projects because
- serving from our domain looks more coherent
- it includes project in our website search
- no advertising
- RTD formats docs differently
- **privacy/data sharing needs to be evaluated and then properly stated** to comply with [GDPR](https://gdpr.eu/what-is-gdpr/) and NF privacy policy etc

Therefore, we'd like the GH-pages deployment to be fixed. For a simple and robust workflow see [GridDataFormats/.github/workflows/docs.yaml](https://github.com/MDAnalysis/GridDataFormats/blob/master/.github/workflows/docs.yaml). You might be able to copy, paste & modify.

**Comment by joaomcteixeira** [comment]
I see.

I have actually implemented that behavior in haddock3, where the pages are deployed automatically to the `gh-pages` branch of the main project and the documentation goes to https://www.bonvinlab.org/haddock3/ address, thus bypassing RTD.

I understand you want the same thing for `mdacli`. It makes much sense.

**Comment by PicoCentauri** [comment]
We already had a gh-pages site but for some reason it stopped working. 

Also we have to fix the readme on pypi...

**Comment by joaomcteixeira** [comment]
> Also we have to fix the readme on pypi...

Okay, that's also an issue. Why is it displaying the file names? Very strange. Will try to look at it asap.
