### ISSUE TITLE
Simplify `analyze_data` method

### ISSUE THREAD

**Issue by PicoCentauri** [MDAnalysis/mdacli#33]
The `analyze_data` method

https://github.com/MDAnalysis/mdacli/blob/78fa3f2fff31fb7f9acf71ee8811ab902369e947/src/mdacli/cli.py#L234

 is our main run method receiving attributes parsed from the cli, creating the universe, runs 
the analysis and saving the results. The function takes all parameters as keyword arguments. However, if one argument is not 
given it fails even if there are default arguments. This should not happen.
Maybe the universe creation, analysis instance creation the run and the saving should split into different functions...

**Comment by joaomcteixeira** [comment]
I agree. We do this after #17 #28
