### ISSUE TITLE
Tests on Windows are failing

### ISSUE THREAD

**Issue by PicoCentauri** [MDAnalysis/mdacli#49]
If running the tests on a Windows machine the following error is produced 

```python
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '{"key1":1}'
```

when running the KwargsDict.

https://github.com/MDAnalysis/mdacli/blob/3c45d8d60026746fccde66c3004107000060a157/tests/test_libcli.py#L24-L39

See for example the tests on the [main branch](https://github.com/MDAnalysis/mdacli/runs/2685364859
).

**Comment by joaomcteixeira** [comment]
try refactoring this:

https://github.com/MDAnalysis/mdacli/blob/3c45d8d60026746fccde66c3004107000060a157/src/mdacli/libcli.py#L31
