### ISSUE TITLE
Implement packge-wide logging system

### ISSUE THREAD

**Issue by joaomcteixeira** [MDAnalysis/mdacli#50]
For another issue, we need to define a general logging library to configure debugging mode etc more nicely. But for now is fine.

_Originally posted by @joaomcteixeira in https://github.com/MDAnalysis/mdacli/pull/45#discussion_r642097601_

**Comment by orbeckst** [comment]
Can you just use the standard logger? MDAnalysis uses it, too; you can start it with [mda.start_logging()](https://docs.mdanalysis.org/stable/documentation_pages/lib/log.html#MDAnalysis.lib.log.start_logging)

**Comment by PicoCentauri** [comment]
I think this is what he got in mind. For the CLI interface I propose a similar logic as we are doing for the [MDAnalysis discord bot ](https://github.com/PicoCentauri/mda-bot/blob/f34e33466999297243be1dc13c49601ba33f8ff0/runner.py#L11-L47)
