### ISSUE TITLE
Visit all Analysis run/result API

### ISSUE THREAD

**Issue by joaomcteixeira** [MDAnalysis/mdacli#7]
*As @PicoCentauri  and I have been discussing in e-mails:*

Verify that all Analysis classes share a common API to run the calculation and retrieve the results. We can also accommodate a small set of APIs through try/catch procedure. A prototype for this code is already in the master branch.

We expected results to be savable to a text file in the disk.

In the future, we can decide if to plot such data o pipe it somewhere else.

Ping to @orbeckst, we might need to discuss with you the best strategy here because this part needs a finer synchronization with the MDAnalysis package itself.

Cheers :smile:

**Comment by orbeckst** [comment]
The best way forward is to involve the broader MDA community (not just me) — see #8 — and in particular let the developer list know where you are with your exciting new project. Once people can look at what's already there and what the general design ideas are then it is easier to raise issues for MDAnalysis.analysis. The jump to 2.0.0 is the ideal time to add bigger changes.

**Comment by joaomcteixeira** [comment]
Perfect, so we will raise an issue/discussion on the devs list to discuss this particular issue. Thanks @orbeckst

**Comment by joaomcteixeira** [comment]
Please read the discussion on #17

**Comment by joaomcteixeira** [comment]
*I am replying [@orbeckst answer](https://github.com/PicoCentauri/mda_cli/pull/17#issuecomment-713067079) in #17 here, because this discussion fits this issue more than the referred PR.*

Hi @orbeckst ,

Thanks for your comments. We don't have a specific document, apart from our e-mail discussions and this issue, and #17 . Yet, what we want to achieve is conceptually simple. We need a common interface on all Analysis Classes so that we can leverage polymorphism to extract the `run` results automatically. More precisely, it doesn't need to be a single interface, it can be more than one as long as it is a number humanly manageable for an automated task as is MDACLI, that is, hopefully, each class won't have its own different method. 

Honestly, I am agnostic to the nature of such a method or attribute. We can decide on whatever is best for MDAnalysis. Though, your last suggestion on the dictionary sounds great and flexible for possible expansions in the future.

It is also not a problem if the common method returns different formats as long as its variety is reduced. We can have a dictionary with different methods ready: `np.save` or  `to_csv` as you well said, and probe them in a `for` loop until the correct one is found and the results saved.

All-and-all, we should aim for saving the results in the most versatile and open format as possible, which is a plain `csv` file that any other program could export and plot the respective data.

Looking forward to hearing your opinions. @PicoCentauri @orbeckst 

Cheers

**Comment by orbeckst** [comment]
So a simple `_analysis_metadata` dict with the names of the result attributes might be enough. (`{'results': True, 'times': True}` – using a dict gives a bit more flexibility than a list in case we need to add more information for each attribute)

MDACLI then takes care of analyzing the datatype of the attribute write it out in a portable manner (i.e., as close to CSV as possible).

I assume that some classes such as DensityAnalysis need special handling to write their output (DX files). Perhaps the dict can then contain the required output handler method?

I think the next step for you should be to put up a skeleton PR with whatever looks like the right approach to you and then let people discuss the draft PR. Having some code and usage examples in front of oneself really focuses the mind as opposed to discussing various options in vaporspace.
