### ISSUE TITLE
some of the API docs are missing

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdacli#73]
Looking at https://mdacli.readthedocs.io/en/latest/api.html , the following sections are **empty**
- [ ] [High-Level API](https://mdacli.readthedocs.io/en/latest/api/cli.html)
- [ ] [Support functions for CLI](https://mdacli.readthedocs.io/en/latest/api/libcli.html)
- [ ] [Results Saving](https://mdacli.readthedocs.io/en/latest/api/save.html)
- [ ] [Logging](https://mdacli.readthedocs.io/en/latest/api/logger.html)
- [ ] [Utilities](https://mdacli.readthedocs.io/en/latest/api/utils.html)

I would expect to see _something_ there.

**Comment by PicoCentauri** [comment]
seems to magically work now: 

https://mdacli.mdanalysis.org/en/latest/api/cli.html
