### ISSUE TITLE
docs on RTD contain Google Analytics

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdacli#77]
Looking at the page source of the docs hosted on RTD I see **"global_analytics_code": "UA-17997319-1",** 

in
```html
<script type="application/json" id="READTHEDOCS_DATA">{"ad_free": false, "api_host": "https://readthedocs.org", "build_date": "2021-11-24T19:10:36Z", "builder": "sphinx", "canonical_url": null, "commit": "b989042f", "docroot": "/docs/rst/", "features": {"docsearch_disabled": false}, "global_analytics_code": "UA-17997319-1", "language": "en", "page": "index", "programming_language": "py", "project": "mdacli", "proxied_api_host": "/_", "source_suffix": ".rst", "subprojects": {}, "theme": "sphinx_rtd_theme", "user_analytics_code": "", "version": "latest"}</script>
```
and
```html
<script type="text/javascript" src="https://assets.readthedocs.org/static/javascript/readthedocs-analytics.js" async="async"></script>
```
Looking at https://assets.readthedocs.org/static/javascript/readthedocs-analytics.js this sets cookies and does send information to Google.

None of this is covered in our [Privacy Policy](https://www.mdanalysis.org/pages/privacy/) so the docs **cannot be served from mdacli.mdanalysis.org** as they are. Anything under mdanalysis.org must comply with our privacy policy.

My recommendation is to switch to GH pages and serve as www.mdanalysis.org/mdacli.

**Comment by orbeckst** [comment]
@PicoCentauri if you disabled the tracking on RTD then close this issue.

**Comment by PicoCentauri** [comment]
It is disabled
