### ISSUE TITLE
move repo to MDAnalysis?

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdacli#8]
Do you want to move the repo under https://github.com/MDAnalysis – you'll have full admin permissions, we can pin it to the top of the repo list, we can easily make docs appear under https://www.mdanalysis.org/mda_cli , and I think it will increase visibility.

- [ ] announce development of mda_cli on the developer list (see https://github.com/PicoCentauri/mda_cli/issues/7#issuecomment-687296020)
- [ ] move repo
- [ ] generate/integrate docs #9 

EDIT: link to doc issue

**Comment by joaomcteixeira** [comment]
I agree with moving the repository to the MDAnalysis main organization. There we can create a `Main_MDACLI_devs` team with both of us to facilitate issue and PR assignment/review.

@PicoCentauri do you want to announce mda_cli on the developer list? I don't mind doing it, just let me know :wink: We can do that after moving the repo.

about the docs I will reply in #9

**Comment by PicoCentauri** [comment]
@joaomcteixeira I can do the announcement and afterwards we can move the repository.

Before we announce I will create a small PR with some code cleanup and an updated README.

**Comment by joaomcteixeira** [comment]
perfect :+1:

**Comment by orbeckst** [comment]
Is there any chance you'd be willing to move the repo by Tuesday? We're working on the CZI proposal, which contains the idea of MDAKits, namely moving code from MDAnalysis.analysis into separate packages that can nevertheless appear under MDAnalysis.analysis (through a registry) if they follow AnalysisBase API, have pip- and conda-installable packages, have standard tests, and any other requirements that we define as necessary. The proposal would contain a Deliverable _Deliverable 2.5.1: Support mdacli (ADD URL) to work with MDAKits._ (under _Milestone 2.5: Support external developers to transition/adapt to MDAKits_). 

It would look better if we could already point to a public URL.

If you don't feel ready yet then that's ok, just let me know as soon as possible, please. Thanks!

Here's the summary for background:

## Proposal summary

MDAnalysis, as one of the most widely used libraries for the analysis of biomolecular simulations and structures, has established a mature core functionality that underpins analysis workflows in academia and industry. Now we focus on two areas of strategic growth: (1) improving the performance of essential core components by rewriting Python code in Cython; and (2) broadening our user and developer base by separating non-core modules into “MDAKits” (MDAnalysis Toolkits, akin to SciPy’s SciKits) to enable the rapid development and dissemination of new components and tools that can be released independently of the main package.

(1): Enabled by continued advances in computing power, the amounts of simulation data produced by biomedical researchers are testing the limits of what is possible with current software and hardware. Coping with these increasing demands requires efficient implementations of the algorithms in MDAnalysis. MDAnalysis is now a mature project whose API has been carefully developed over the last decade. Because the user-facing API is stable and the underlying data structures have been well tested, we are now in a position to move core components beyond Python to a faster Cython-generated C++ representation, mirroring design choices made in other high performance Python libraries such as Pandas.
This change will improve performance across the entire library and future-proof the package for the next generation of biomedical simulations.  Moreover, a C++ representation of data structures will enable tighter integration with other tools in this area, furthering the pursuit of interoperability (a focus of Aim (2)).

(2): Separating our non-core modules into MDAKits decouples the relatively slow development cycle of mature core components from the faster changes in newer parts of the codebase, decreasing a barrier to code contribution. We will establish a cookiecutter template for new repositories of MDAnalysis centric libraries and tools, with input from organisations such as the Molecular Sciences Software Institute (MolSSI) to ensure best-practices. This will be supplemented by improved documentation and tutorials for using the MDAnalysis API. Authors of MDAKits will be able to request a review to be integrated into MDAnalysis. We will leverage the existing, mature Python packaging system so that users can easily install these additional packages alongside MDAnalysis, publicizing it to a large audience of interested parties. We will work with editors at journals such as the Journal of Open Source Software (JOSS) to streamline a direct pathway to publication, combining scientific peer review (at the journal) and code review (for MDAnalysis) to ensure that the code is scientifically valid. This gives tool developers a citable paper for tested code and users peer-reviewed research to refer to, driving transparent and reproducible research in the biomolecular simulation community. We will demonstrate the development and integration of an MDAKit into MDAnalysis by porting many of our existing analysis modules and our "converters" module to MDAKits. Converters have been key to achieving interoperability with other simulation and analysis packages, establishing MDAnalysis as a bridge between different simulation communities and growing our user-base. Developing converters independently will accelerate the expansion of interoperability to new packages.

**Comment by orbeckst** [comment]
We can link to https://github.com/PicoCentauri/mda_cli , of course, but it's not obvious that the project is closely tied to MDAnalysis.

**Comment by PicoCentauri** [comment]
From my side we can move the repo at any time. I think @joaomcteixeira also agrees. 
If the PRs #23 and #17 are merged we should also have a first working version.

**Comment by orbeckst** [comment]
That's done!

**Comment by joaomcteixeira** [comment]
Hi @orbeckst , sorry couldn't read this before. Yes, I agree you moving the repository (you already did).

On another note, I am sure you and the MDA main dev team already know, but just in case, [pybind11](https://pybind11.readthedocs.io/en/stable/) is given very good results in bridging Python and C++ modules. I have tested it in some private examples and it works pretty well. The binding function is relatively easy to write and one can then import the C++ functions directly in the respective Python module. I am not a C++ developer, but pybind11 advocates they are reduced much heaviness from previous approaches.

Cheers and best luck for the fellowship!

**Comment by joaomcteixeira** [comment]
> From my side we can move the repo at any time. I think @joaomcteixeira also agrees.
> If the PRs #23 and #17 are merged we should also have a first working version.

We will try to have this done by this week. @PicoCentauri do you have time for any night coding experience? :wink:

**Comment by PicoCentauri** [comment]
Night shifts are the best!

**Comment by joaomcteixeira** [comment]
Have a look at https://duckly.com we may use it.
Tomorrow Tuesday 18th at 10PM Berlin? We can give it a couple of hours. We can repeat it again other days if wish/needed.
Cheers! :rocket:

**Comment by PicoCentauri** [comment]
Let's do it!
