### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdacli#9]
To give users and developers an idea how to work with mda_cli there should be at least minimal docs. I  recommend you set up sphinx docs and use the MDA templates as it's easier for users to have same navigation and markup conventions.

Topics that would be important
- motivation
- philosophy (what is the underlying key idea/approach?)
- high-level view (examples of what can done)
  - user side
  - developer side
- specific examples (for developers: how to use the tool box)

**Comment by joaomcteixeira** [comment]
Perfect,

We need to go into the structure of MDA documentation to integrate it properly. I know you have been updating it strongly :wink: 
We will keep in touch!

**Comment by orbeckst** [comment]
The docs would be separate from the mda docs. They would appear under https://www.mdanalysis.org/mda_cli. We will link from the MDAnalysis.analysis docs to them. However, having the docs separate has the advantage that they can be updated and revised on much faster schedule than main MDA.

**Comment by joaomcteixeira** [comment]
:+1: we will keep you posted.

**Comment by orbeckst** [comment]
basic documentation is now available on RTD https://mdacli.readthedocs.io/en/latest/
